# Generated by Django 4.2.11 on 2024-03-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cardurl',
            field=models.ImageField(blank=True, null=True, upload_to='service_cardUrl/'),
        ),
    ]
