# Generated by Django 4.2.11 on 2024-03-06 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_service_cardurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cardurl',
            field=models.ImageField(blank=True, null=True, upload_to='service_cardUrl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
