# Generated by Django 4.2.11 on 2024-03-06 20:36

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_service_cardurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cardurl',
            field=models.ImageField(blank=True, null=True, upload_to='service_cardUrl/', validators=[myapp.models.SVGValidator()]),
        ),
    ]
