# Generated by Django 4.2.11 on 2024-03-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_service_cardurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='percentage',
        ),
    ]
